// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTpxgkDCso8ZNJf1UfInQOmy0oT28FMeY',
    appId: '1:742691703762:web:ac074d53cd073b55f2960b',
    messagingSenderId: '742691703762',
    projectId: 'twitterclone-28ec4',
    authDomain: 'twitterclone-28ec4.firebaseapp.com',
    databaseURL: 'https://twitterclone-28ec4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitterclone-28ec4.appspot.com',
    measurementId: 'G-VEC6J9CV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfSW161cY3ijPhrbvQbOcYbuGVQKkJEk',
    appId: '1:742691703762:android:fa25662ea3367669f2960b',
    messagingSenderId: '742691703762',
    projectId: 'twitterclone-28ec4',
    databaseURL: 'https://twitterclone-28ec4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitterclone-28ec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-JndRiZSSEux2Aw83SxwX9ZVozc9Chw',
    appId: '1:742691703762:ios:2b65b4d17810a31af2960b',
    messagingSenderId: '742691703762',
    projectId: 'twitterclone-28ec4',
    databaseURL: 'https://twitterclone-28ec4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitterclone-28ec4.appspot.com',
    iosClientId: '742691703762-gd6qg1qigrma1kjcqmknhq91ma19oc1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo-JndRiZSSEux2Aw83SxwX9ZVozc9Chw',
    appId: '1:742691703762:ios:614a5b9f072fee27f2960b',
    messagingSenderId: '742691703762',
    projectId: 'twitterclone-28ec4',
    databaseURL: 'https://twitterclone-28ec4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitterclone-28ec4.appspot.com',
    iosClientId: '742691703762-r9rggpe4upm9skf6vk0ge2mu56dv8ntk.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
